### ISSUE TITLE
Error while running astrosource

### ISSUE THREAD

**Issue by redeaglekr** [zemogle/astrosource#18]
I was using the code astrosource,  to carryout  photometry from LCO  reduced (BANZAI) images. I ran the command

"astrosource --ra XXXXXXX --dec XXXXXXX --indir  /home/photometry/lcogtdata-2021XXXXX -XX/  --full --verbose "

Where lcogtdata-2021XXXXX -XX is the folder in which images were stored.
 
I found that the code runs well until it  finds comparison stars, but then received the error as:

Traceback (most recent call last):
  File "/home/sreenivas/.local/bin/astrosource", line 11, in <module>
    load_entry_point('astrosource==1.5.2', 'console_scripts', 'astrosource')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/XXXXX/.local/lib/python3.8/site-packages/astrosource-1.5.2-py3.8.egg/astrosource/main.py", line 88, in main
    ts.analyse()
  File "/home/XXXXX/.local/lib/python3.8/site-packages/astrosource-1.5.2-py3.8.egg/astrosource/astrosource.py", line 51, in analyse
    find_comparisons(self.targets, self.indir, self.usedimages, thresholdCounts=self.thresholdcounts)
  File "/home/XXXXXXX/.local/lib/python3.8/site-packages/astrosource-1.5.2-py3.8.egg/astrosource/comparison.py", line 63, in find_comparisons
    compFile = remove_stars_targets(parentPath, compFile, acceptDistance, targets, removeTargets)
  File "/home/XXXXXXX/.local/lib/python3.8/site-packages/astrosource-1.5.2-py3.8.egg/astrosource/comparison.py", line 312, in remove_stars_targets
    variableResult=v.query_region(avgCoord, '0.33 deg', catalog='VSX')['B/vsx/vsx']
  File "/home/XXXXXXX/.local/lib/python3.8/site-packages/astroquery/utils/commons.py", line 251, in __getitem__
    raise TypeError("TableLists can only be indexed with the "

TypeError: TableLists can only be indexed with the named keys and integers.

It would be nice if you could  help me with this (any commands, arguments )??

**Comment by zemogle** [comment]
Thanks for reporting this. There are not enough viable comparison stars. Astrosource should catch this and exit gracefully. I need some more time to check if there really are not enough stars before I make a new release.

**Comment by zemogle** [comment]
Can I ask what your target RA and Dec is?

**Comment by zemogle** [comment]
This is now fixed in the current release `1.6.0`
